version: 0.0
os: linux

files:
  - source: target/
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: scripts/permissions.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
